### ISSUE TITLE
ReferenceError: event is not defined

### ISSUE THREAD

**Issue by pentium10** [MarianoMolina/project_alice#17]
the latest main repo doesn't build 

```
backend-1       | /app/node_modules/@lmstudio/sdk/dist/index.cjs:9840                                                                                                                                             
backend-1       |         this.errored(event);                                                                                                                                                                    
backend-1       |                      ^                                                                                                                                                                          
backend-1       | 
backend-1       | ReferenceError: event is not defined                                                                                                                                                            
backend-1       |     at AuthenticatedWsClientTransport.onWsError (/app/node_modules/@lmstudio/sdk/dist/index.cjs:9840:22)                                                                                        
backend-1       |     at WebSocket.<anonymous> (/app/node_modules/@lmstudio/sdk/dist/index.cjs:9768:61)                                                                                                           
backend-1       |     at callListener (/app/node_modules/ws/lib/event-target.js:290:14)                                                                                                                           
backend-1       |     at WebSocket.onError (/app/node_modules/ws/lib/event-target.js:230:9)
backend-1       |     at WebSocket.emit (node:events:513:28)                                                                                                                                                      
backend-1       |     at emitErrorAndClose (/app/node_modules/ws/lib/websocket.js:1041:13)                                                                                                                        
backend-1       |     at ClientRequest.<anonymous> (/app/node_modules/ws/lib/websocket.js:881:5)                                                                                                                  
backend-1       |     at ClientRequest.emit (node:events:513:28)                                                                                                                                                  
backend-1       |     at Socket.socketErrorListener (node:_http_client:494:9)
backend-1       |     at Socket.emit (node:events:513:28)                                                                                                                                                         
backend-1 exited with code 1
```

**Comment by MarianoMolina** [comment]
Yes, I've been looking at it today. Seems to be an uncaught error in the LM Studio sdk when the LM Studio server is not online. 
Check here:

https://github.com/lmstudio-ai/lmstudio.js/issues/149

If you pull the newest version I have wrapped this so it stops having issues until they fix it. 

Thanks!
